- Vanilla-Js-Playlist/css/styles.css
- Vanilla-Js-Playlist/index.html
- Vanilla-Js-Playlist/scripts/main.js
> Js tutorial tp

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> label updation added

- Vanilla-Js-Playlist/css/styles.css
- Vanilla-Js-Playlist/index.html
- Vanilla-Js-Playlist/scripts/main.js
> Yay I was able to manipulate dom

- Vanilla-Js-Playlist/index.html
- Vanilla-Js-Playlist/scripts/main.js
> Took the input and configured the description of the expense

- Vanilla-Js-Playlist/scripts/main.js
> Playing with the arrays and handling the data structure

- Vanilla-Js-Playlist/index.html
- Vanilla-Js-Playlist/scripts/main.js
> Learned about the templating in js

- Front-End/HTTP-Basics/Learning.md
> Learned the HTTP basics

- Front-End/HTML5-CSS3-Basics/Google-Landing-Page-Project/index.html
- Front-End/HTML5-CSS3-Basics/Google-Landing-Page-Project/style.css
> Google homepage partially made

- Front-End/HTML5-CSS-Advance/asideTag.html
:ballot_box_with_check: Learnt the header, footer, aside, section tags in the HTML five symantics
> :ballot_box_with_check: Learnt the header, footer, aside, section tags

- Front-End/HTML5-CSS-Advance/conditionalComments.html
- Front-End/HTML5-CSS-Advance/logicalAndPhysicalTags.html
Did all three of them with proper comments
> :memo:  Logical, Physical & Conditional comments learned

- Front-End/HTML5-CSS-Advance/entities.html
> :bookmark:  Learned the entities in the html

- Front-End/HTML5-CSS-Advance/input.html
> ✅ Forms part 1 done

- Front-End/HTML5-CSS-Advance/input.html
> :video_camera:  Second video of forms done

- Front-End/HTML5-CSS-Advance/input.html
- Selecting the specific format amongst the file
- Autofocus added to the element
- Disabled attribute added
- Linked two different sections of the form using the same id
- Added Placeholder and Attribute to select multiple files at once
> :package:  Forms all attribute done

- Front-End/HTML5-CSS-Advance/input.html
> :ballot_box_with_check:  Field set to required

- Front-End/HTML5-CSS-Advance/cssSpecificity.md
- Front-End/HTML5-CSS-Advance/frames.html
> :1st_place_medal:  HTML Advanced Completed

- Front-End/HTML5-CSS-Advance/boxModel.md
> Added the box model for the css advance first topic

- Front-End/HTML5-CSS-Advance/variables.css
- Front-End/HTML5-CSS-Advance/variables.html
> :checkered_flag:  Css variables completed

- Front-End/HTML5-CSS-Advance/calc.css
- Front-End/HTML5-CSS-Advance/calc.html
> :heavy_check_mark:  Learned the calc function in css

- Front-End/HTML5-CSS-Advance/classes.css
- Front-End/HTML5-CSS-Advance/pseudoClasses.html
> Pseudo Classes addd

- Front-End/HTML5-CSS-Advance/elements.css
- Front-End/HTML5-CSS-Advance/pseudoElements.html
> Pseudo elements like ::before & ::after completed

- .vscode/settings.json
- Front-End/HTML5-CSS-Advance/attr.css
- Front-End/HTML5-CSS-Advance/attrFunction.html
> Attr() function added

- Front-End/HTML5-CSS-Advance/advanceSelectors.css
- Front-End/HTML5-CSS-Advance/advanceSelectors.html
> update: :rocket: Added the Css Selectors and Attribute selectors

- Front-End/HTML5-CSS-Advance/mediaQueries.css
- Front-End/HTML5-CSS-Advance/mediaQueries.html
> fix: :rocket: Added the media tags document and methods

- Front-End/HTML5-CSS-Advance/animation.css
- Front-End/HTML5-CSS-Advance/animation.html
> feat: :rocket: : Frontend Update

- .github/ISSUE_TEMPLATE/feature_request.md
> update: :memo: Updating the local branch

- Front-End/HTML5-CSS-Advance/grid2.css
- Front-End/HTML5-CSS-Advance/grid2.html
> fix: :hammer_and_wrench:  Added the nested grids

- Front-End/HTML5-CSS-Advance/grid3.css
- Front-End/HTML5-CSS-Advance/grid3.html
> feat: :white_check_mark: Grid done and Css advance too

- Front-End/Javascript/Javascript-Basics/variables.html
- Front-End/Javascript/Javascript-Basics/variables.js
> feat: :rocket: Variable in the javascript added

- Front-End/Javascript/Javascript-Basics/dataTypes.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
- Front-End/Javascript/Javascript-Basics/variables.html
- Front-End/Javascript/Javascript-Basics/variables.js
> Update: :fire:  Frontend

- Front-End/Javascript/Javascript-Basics/functions.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> upd: :fire:  Update Frontend with function parameteres

- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
- Front-End/Javascript/Javascript-Basics/returnFunction.js
> feat: :rocket: Learned the returning of the functions

- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
- Front-End/Javascript/Javascript-Basics/scoping.js
> feat: :rocket: Scoping added and learned about hoisting

- Front-End/Javascript/Javascript-Basics/alertPromptConfirm.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> feat: :rocket: Confirm, Prompt, alert added

- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
- Front-End/Javascript/Javascript-Basics/object.js
> Add :hammer: Understood the objects in js

- Front-End/Javascript/Javascript-Basics/object.js
> feat: :heavy_plus_sign: Ways to access the elements in the objects added

- Front-End/Javascript/Javascript-Basics/array.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> feat: :fire: Learned about the array and manipulated them

- Front-End/Javascript/Javascript-Basics/conditional.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> feat: :heavy_plus_sign: Practiced the conditional statement

- Front-End/Javascript/Javascript-Basics/incrementAndDecrement.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> Add :fire: Added and learned the increment and decrement

- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
- Front-End/Javascript/Javascript-Basics/logicalOperator.js
> Add :rocket: Added the Logic operators

- Front-End/Javascript/Javascript-Basics/bitwiseOperator.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> Add :fire: Added Bitwise Operators

- Front-End/Javascript/Javascript-Basics/forLoop.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> Add: :heavy_plus_sign: For loop added b8a142f

- Front-End/Javascript/Javascript-Basics/doWhileLoop.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
- Front-End/Javascript/Javascript-Basics/whileLoop.js
> Loops added :+1: 

- Front-End/Javascript/Javascript-Basics/breakContinueReturn.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> Add: :heavy_plus_sign: Added Break, Continue, Return

- Front-End/Javascript/Javascript-Basics/arrayFunction.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> Add: :hammer_and_wrench: Javascript array functions added

- Front-End/Javascript/Javascript-Basics/intervalAndTimeout.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> Add: :heavy_plus_sign: setInterval & setTimeout added

- Front-End/Javascript/Javascript-Basics/eventHandlers.js
- Front-End/Javascript/Javascript-Basics/intervalAndTimeout.js
- Front-End/Javascript/Javascript-Basics/javascriptBasics.html
> Add: :rocket: Onclick Event Handler added

- Front-End/Javascript-Intermidiate/CRUD.js
- Front-End/Javascript-Intermidiate/index.html
> Removing & Replacing learned

- Front-End/Javascript-Intermidiate/events.js
- Front-End/Javascript-Intermidiate/index.html
>  Add: :rocket: Basic event listeners added

- Front-End/Javascript-Intermidiate/index.html
- Front-End/Javascript-Intermidiate/localAndSessionStorage.js
> feat: :rocket: Local and Session storage added

- Front-End/Javascript-Intermidiate/API/currency.html
- Front-End/Javascript-Intermidiate/API/exchange.js
- Front-End/Javascript-Intermidiate/editableDiv.js
- Front-End/Javascript-Intermidiate/index.html
> Feat: :rocket: API integration learned 

- Back-End/Tutorial-1-CodeWithHarry/.gitignore
- Back-End/Tutorial-1-CodeWithHarry/index.js
- Back-End/Tutorial-1-CodeWithHarry/package-lock.json
- Back-End/Tutorial-1-CodeWithHarry/package.json
- Back-End/Tutorial-1-CodeWithHarry/second.js
> Started with Common JS Module. (Node JS)

- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/6-Npm-Package-Manager/index.js
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/6-Npm-Package-Manager/package-lock.json
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/6-Npm-Package-Manager/package.json
> Leaned the working of the npm package manager

- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/7-Create-First-Express-App/.gitignore
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/7-Create-First-Express-App/app.js
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/7-Create-First-Express-App/package-lock.json
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/7-Create-First-Express-App/package.json
> Created first Express app and tested it on postman

- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/8-Starting-with-template-engine/.gitignore
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/8-Starting-with-template-engine/app.js
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/8-Starting-with-template-engine/package-lock.json
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/8-Starting-with-template-engine/package.json
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/8-Starting-with-template-engine/static/file.js
- Back-End/NodeJs/Tutorial-2-CodeWithHarry(Series)/8-Starting-with-template-engine/views/hello.pug
> Learnt templating html files using pug

- Back-End/NodeJs/Practice-Projects/BlogSite/.gitignore
- Back-End/NodeJs/Practice-Projects/BlogSite/data/blogsData.js
- Back-End/NodeJs/Practice-Projects/BlogSite/index.js
- Back-End/NodeJs/Practice-Projects/BlogSite/package-lock.json
- Back-End/NodeJs/Practice-Projects/BlogSite/package.json
- Back-End/NodeJs/Practice-Projects/BlogSite/routes/blogServer.js
- Back-End/NodeJs/Practice-Projects/BlogSite/views/blogHome.handlebars
- Back-End/NodeJs/Practice-Projects/BlogSite/views/blogHome.html
- Back-End/NodeJs/Practice-Projects/BlogSite/views/blogPage.html
- Back-End/NodeJs/Practice-Projects/BlogSite/views/blogPost.handlebars
- Back-End/NodeJs/Practice-Projects/BlogSite/views/home.handlebars
- Back-End/NodeJs/Practice-Projects/BlogSite/views/index.html
- Back-End/NodeJs/Practice-Projects/BlogSite/views/layouts/main.handlebars
> Made Blog site, With templating and routing

- Back-End/NodeJs/Practice-Projects/BlogSite/index.js
> Add a bit more of context

- Back-End/MongoDB/4-Deleting-From-DB.md
- Back-End/MongoDB/5-Update-Data-In-DB.md
> feat: :file_cabinet: MongoDB Setup and CRUD operations added

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/index.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/tourRoutes.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/server.js
> Params middleware [Backend]

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/tourRoutes.js
> Params and Chaining middleware done

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/config.env
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/index.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package-lock.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/server.js
> Backend Learning Update

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/.gitignore
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package-lock.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/server.js
> MongoDB connections

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/tourRoutes.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/server.js
> feat: Started with MVC architecture

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/.env-example
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/config.env
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/tourModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/tourRoutes.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/server.js
> CRUD Completed 🥳

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/dev-data/data/import-data-script.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/tourModel.js
> feat: Advance modeling data and running script

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/README.md
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
> Filtering the response using query and other functions

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
> feat: Sorted the reponse with specified field in the query (#134)

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
> Learnt response formatting

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
> Chaining function using classes

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/tourRoutes.js
> feat: :boom: Aggregation pipeline learned and setup

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/tourRoutes.js
> Aggregation pipeline learnt and added

- .github/FUNDING.yml
> feat: :boom: Updated Link

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/tourModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package-lock.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package.json
> Document, Query, Aggregate middlewares "pre" and "post" hooks added

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/tourModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package-lock.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package.json
> Finished using mongodb with mongoose module

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/index.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package.json
> Started with Error Handling module

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/index.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/utils/catchAsync.js
> Catching the errors in async function done

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/errorController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/tourController.js
> Handling invalid URLs and Database ID's

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/errorController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/tourModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/server.js
> Error Handling Completed

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/authController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/userModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/userRoutes.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/server.js
> Authorization and security started, created user model and route for signup

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/server.js
Solves deprecation mistake regarding #154
#154
[Reference](https://stackoverflow.com/questions/57895175/server-discovery-and-monitoring-engine-is-deprecated)
> [fix]: deprecation regarding #154

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/.env-example
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/authController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/userModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package-lock.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package.json
> Authenticating Users and Hashing passwords learned and added

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/authController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/userController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/userModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/tourRoutes.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/userRoutes.js
> Logging in Users and routes security

- README.md
> Frontend & Backend repos added

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/.env-example
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/authController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/userModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package-lock.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/package.json
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/userRoutes.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/utils/emailSender.js
> Resetting the Password by hashing a random string and emailing it to the user

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/authController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/userModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/userRoutes.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/utils/emailSender.js
> Password reset logic added with few emailing bugs

- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/controllers/authController.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/models/userModel.js
- Back-End/Jonas Node+MongoDB Course/Nodejs + ExpressJS/Express-API/routes/userRoutes.js
> Updating the user password if the user is already logged in

- Back-End/api-practice/bookstore/.gitignore
- Back-End/api-practice/bookstore/package-lock.json
- Back-End/api-practice/bookstore/package.json
- Back-End/api-practice/bookstore/steps-followup.md
> feat: Project initiated and imp packages added

- Back-End/api-practice/bookstore/index.js
- Back-End/api-practice/bookstore/package.json
- Back-End/api-practice/bookstore/routes/booksRoute.js
- Back-End/api-practice/bookstore/steps-followup.md
> BookStore Api 

- Back-End/api-practice/bookstore/.eslintrc.json
- Back-End/api-practice/bookstore/.prettierrc
- Back-End/api-practice/bookstore/controllers/booksController.js
- Back-End/api-practice/bookstore/index.js
- Back-End/api-practice/bookstore/package-lock.json
- Back-End/api-practice/bookstore/package.json
> Added eslint and prettier with all the configs and packages

- Back-End/api-practice/bookstore/controllers/booksController.js
- Back-End/api-practice/bookstore/routes/booksRoute.js
> feat: GET route implemented for getting a single book

- Back-End/api-practice/bookstore/controllers/booksController.js
- Back-End/api-practice/bookstore/models/booksModel.js
- Back-End/api-practice/bookstore/routes/booksRoute.js
> feat: Resolved the /POST method error by adding body parsor

- Back-End/api-practice/bookstore/models/booksModel.js
> feat: Array segment improved

- Back-End/api-practice/bookstore/controllers/userController.js
- Back-End/api-practice/bookstore/index.js
- Back-End/api-practice/bookstore/models/userModel.js
- Back-End/api-practice/bookstore/package-lock.json
- Back-End/api-practice/bookstore/package.json
- Back-End/api-practice/bookstore/routes/userRoute.js
> User route and modes started

- Back-End/api-practice/bookstore/controllers/authController.js
- Back-End/api-practice/bookstore/controllers/booksController.js
- Back-End/api-practice/bookstore/controllers/errorController.js
- Back-End/api-practice/bookstore/controllers/userController.js
- Back-End/api-practice/bookstore/package.json
- Back-End/api-practice/bookstore/routes/userRoute.js
- Back-End/api-practice/bookstore/util/catchAsync.js
> Error handing and production server script added

- Back-End/api-practice/bookstore/controllers/errorController.js
- Back-End/api-practice/bookstore/index.js
- Back-End/api-practice/bookstore/models/userModel.js
- Back-End/api-practice/bookstore/package-lock.json
- Back-End/api-practice/bookstore/package.json
- Back-End/api-practice/bookstore/routes/booksRoute.js
- Back-End/api-practice/bookstore/routes/userRoute.js
> fix: Errors handled

- Back-End/api-practice/bookstore/controllers/userController.js
- Back-End/api-practice/bookstore/models/userModel.js
- Back-End/api-practice/bookstore/package.json
> feat: wrapping up the error handling with some user functions

- Back-End/api-practice/bookstore/index.js
- Back-End/api-practice/bookstore/server.js
> feat: Web Security middlewares and server safe closures added

- Back-End/api-practice/bookstore/cucumber.js
- Back-End/api-practice/bookstore/index.js
- Back-End/api-practice/bookstore/package-lock.json
- Back-End/api-practice/bookstore/package.json
- Back-End/api-practice/bookstore/routes/booksRoute.js
- Back-End/api-practice/bookstore/tests/features/support/steps.js
- Back-End/api-practice/bookstore/tests/features/test.feature
> feat: Added tests to check the endpoints

- Back-End/api-practice/bookstore/Dockerfile
> feat: Dockerized the bookstore api

- Front-End/React JS/Code_With_Harry_Tutorial/textutils/package-lock.json
- Front-End/React JS/Code_With_Harry_Tutorial/textutils/package.json
- Front-End/React JS/Code_With_Harry_Tutorial/textutils/src/components/About/About.js
- Front-End/React JS/Code_With_Harry_Tutorial/textutils/src/components/App/App.js
- Front-End/React JS/Code_With_Harry_Tutorial/textutils/src/components/Navbar/Navbar.js
> feat: React routes added and setup

- Back-End/api-practice/bookstore/kubernetes/bookstore-deployment.yaml
- Back-End/api-practice/bookstore/kubernetes/bookstore-service.yaml
> feat: Added config files for deployment on Kubernetes [Part 1]

- Front-End/React JS/Practice-Projects/portfolio2/package-lock.json
- Front-End/React JS/Practice-Projects/portfolio2/package.json
- Front-End/React JS/Practice-Projects/portfolio2/public/index.html
- Front-End/React JS/Practice-Projects/portfolio2/src/components/About/About.css
- Front-End/React JS/Practice-Projects/portfolio2/src/components/About/About.js
- Front-End/React JS/Practice-Projects/portfolio2/src/components/App/App.js
- Front-End/React JS/Practice-Projects/portfolio2/src/components/Home/Home.css
- Front-End/React JS/Practice-Projects/portfolio2/src/components/Home/Home.js
- Front-End/React JS/Practice-Projects/portfolio2/src/components/Navbar/Navbar.js
> Frontend Updates

- Front-End/React JS/Practice-Projects/portfolio2/public/index.html
- Front-End/React JS/Practice-Projects/portfolio2/src/components/About/About.js
> feat: Added the My Journey timeline added

- Front-End/React JS/Practice-Projects/portfolio2/src/components/Contact/Contact.css
- Front-End/React JS/Practice-Projects/portfolio2/src/components/Contact/Contact.js
> feat: Added contact form final styles

- Front-End/React JS/Practice-Projects/dog-info/src/components/Card/Card.css
- Front-End/React JS/Practice-Projects/dog-info/src/components/Card/Card.js
> feat: :rocket: Api added rendering cards remaining

- Front-End/React JS/Practice-Projects/news-monkey/src/components/App/App.js
- Front-End/React JS/Practice-Projects/news-monkey/src/components/ButtonSwitch/ButtonSwitch.css
- Front-End/React JS/Practice-Projects/news-monkey/src/components/ButtonSwitch/ButtonSwitch.js
- Front-End/React JS/Practice-Projects/news-monkey/src/components/Card/Card.css
- Front-End/React JS/Practice-Projects/news-monkey/src/components/Card/Card.js
- Front-End/React JS/Practice-Projects/news-monkey/src/components/ColorChange/ColorChange.css
- Front-End/React JS/Practice-Projects/news-monkey/src/components/ColorChange/ColorChange.js
- Front-End/React JS/Practice-Projects/news-monkey/src/context/styleContext.js
- Front-End/React JS/Practice-Projects/news-monkey/src/context/styleState.js
- Front-End/React JS/Practice-Projects/news-monkey/src/index.js
> Wrapping News-Monkey

- README.md
Fixes #275 
Added header image generated using [GitHub Socialify](https://socialify.git.ci/) to `README.md` file. Which display title, description, stars, forks, issues & pulls of the repository.
> feat: Added header image to README.md

- Front-End/Material UI/The Net Ninja Tutorial/HandsOn with Components/src/components/App/App.js
- Front-End/Material UI/The Net Ninja Tutorial/HandsOn with Components/src/components/Pages/LearnLists.js
- Front-End/Material UI/The Net Ninja Tutorial/HandsOn with Components/src/components/Pages/LearnParmanentDrawer.js
> Material UI progress

- Front-End/Material UI/The Net Ninja Tutorial/HandsOn with Components/src/components/App/App.js
- Front-End/Material UI/The Net Ninja Tutorial/HandsOn with Components/src/components/Pages/LearnAppBar.js
> Progressing in Material UI

- Front-End/Material UI/Practice Projects/anime-suggester/src/components/SuggestionBox/v1.js
> feat: api fetching and useEffect trials

- Front-End/Material UI/Practice Projects/anime-suggester/src/components/AnimeCard/AnimeCard.js
- Front-End/Material UI/Practice Projects/anime-suggester/src/components/SuggestionBox/SuggestionBox.js
- Front-End/Material UI/Practice Projects/anime-suggester/src/dev-data/anime.json
> Completing Material UI project 1

- Front-End/Material UI/Practice Projects/anime-suggester/src/components/SuggestionBox/SuggestionBox.js
> fix: :bug: range extended from 1-10 to 1-100

- Front-End/Material UI/Practice Projects/spotify-clone/src/components/NavBar/NavBar.js
- Front-End/Material UI/Practice Projects/spotify-clone/src/components/SideDrawer/SideDrawer.js
- Front-End/Material UI/Practice Projects/spotify-clone/src/index.js
> Spotify UI clone

- Front-End/Tailwind CSS/Code With Harry Tutorial/.gitignore
- Front-End/Tailwind CSS/Code With Harry Tutorial/first.html
- Front-End/Tailwind CSS/Code With Harry Tutorial/landing.html
- Front-End/Tailwind CSS/Code With Harry Tutorial/package-lock.json
- Front-End/Tailwind CSS/Code With Harry Tutorial/package.json
- Front-End/Tailwind CSS/Code With Harry Tutorial/tailwind.config.js
> feat: :zap: Started Tailwind css with basic setup

- Front-End/Tailwind CSS/React Js X Tailwind Css/landing-page/package-lock.json
- Front-End/Tailwind CSS/React Js X Tailwind Css/landing-page/package.json
- Front-End/Tailwind CSS/React Js X Tailwind Css/landing-page/public/index.html
- Front-End/Tailwind CSS/React Js X Tailwind Css/landing-page/src/Components/App/App.js
- Front-End/Tailwind CSS/React Js X Tailwind Css/landing-page/src/Components/Landing/Landing.js
- Front-End/Tailwind CSS/React Js X Tailwind Css/landing-page/src/Components/Navbar/Navbar.js
- Front-End/Tailwind CSS/React Js X Tailwind Css/landing-page/src/index.js
- Front-End/Tailwind CSS/React Js X Tailwind Css/landing-page/tailwind.config.js
> Tailwind implementation

- Front-End/Angular/CWH-Tutorial/todo-list/angular.json
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todo-item/todo-item.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todo-item/todo-item.component.spec.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todo-item/todo-item.component.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todos/todos.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todos/todos.component.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/Todo.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/app.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/app.module.ts
- Front-End/Angular/CWH-Tutorial/todo-list/tsconfig.json
> Building Todo list app in Angular (1)

- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/add-todo/add-todo.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/add-todo/add-todo.component.spec.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/add-todo/add-todo.component.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todo-item/todo-item.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todos/todos.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todos/todos.component.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/app.module.ts
> feat: Angular todo app (2)

- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todo-item/todo-item.component.css
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todo-item/todo-item.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todo-item/todo-item.component.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todos/todos.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todos/todos.component.ts
> Angular todo project (3)

- Front-End/Angular/CWH-Tutorial/todo-list/angular.json
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/about/about.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/about/about.component.spec.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/about/about.component.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/MyComponents/todos/todos.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/app-routing.module.ts
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/app.component.html
- Front-End/Angular/CWH-Tutorial/todo-list/src/app/app.module.ts
> Angular todo list app (4)

- Back-End/api-practice/train-api/.gitignore
- Back-End/api-practice/train-api/app.js
- Back-End/api-practice/train-api/controllers/trainsController.js
- Back-End/api-practice/train-api/package-lock.json
- Back-End/api-practice/train-api/package.json
- Back-End/api-practice/train-api/routes/trainRoutes.js
- Back-End/api-practice/train-api/server.js
> Practicing and recalling api

- Back-End/api-practice/train-api/controllers/trainsController.js
- Back-End/api-practice/train-api/dev-data/json/trains.json
- Back-End/api-practice/train-api/package-lock.json
- Back-End/api-practice/train-api/package.json
- Back-End/api-practice/train-api/server.js
> Database connections and handling

- Projects/guess-tech-word/.gitignore
- Projects/guess-tech-word/backend/app.js
- Projects/guess-tech-word/backend/package-lock.json
- Projects/guess-tech-word/backend/package.json
- Projects/guess-tech-word/backend/server.js
- Projects/guess-tech-word/docs/design-doc.md
> Guess tech words game [1]

- Projects/guess-tech-word/backend/app.js
- Projects/guess-tech-word/backend/controllers/guessController.js
- Projects/guess-tech-word/backend/routes/guessRoutes.js
> Tech word guesser [2]

- Projects/guess-tech-word/backend/dev-data/json/list.json
- Projects/guess-tech-word/backend/models/techWordModel.js
> Guess Tech Word [2]
